runtime: python311

entrypoint: uvicorn main:appFast --host 0.0.0.0 --port $PORT

automatic_scaling:
  max_instances: 5

env_variables:
  GCP_PROJECT: "project-73f86bbc-37a9-4385-af6"
  GCP_LOCATION: "europe-west3"
  BUCKET_NAME: "clients-avatars-bucket"
  TASK_QUEUE: "clients-queue"